set(_AMENT_PACKAGE_NAME "MPPI-Generic")
set(MPPI-Generic_VERSION "0.1.0")
set(MPPI-Generic_MAINTAINER "Arjun Jagdish Ram <arjun.ram@tier4.jp>")
set(MPPI-Generic_BUILD_DEPENDS )
set(MPPI-Generic_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(MPPI-Generic_BUILD_EXPORT_DEPENDS )
set(MPPI-Generic_BUILDTOOL_EXPORT_DEPENDS )
set(MPPI-Generic_EXEC_DEPENDS )
set(MPPI-Generic_TEST_DEPENDS )
set(MPPI-Generic_GROUP_DEPENDS )
set(MPPI-Generic_MEMBER_OF_GROUPS )
set(MPPI-Generic_DEPRECATED "")
set(MPPI-Generic_EXPORT_TAGS)
list(APPEND MPPI-Generic_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
